### ISSUE TITLE
[Chatter Load issues] Failed to load the following package: chatter

### ISSUE THREAD

**Issue by chris100186** [bobloy/Fox-V3#108]
When i try to load chatter i get the following error in the console
`[2020-08-02 20:29:34] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/redbot/core/core_commands.py", line 119, in _load
    await bot.load_extension(spec)
  File "/home/ubuntu/redenv/lib/python3.8/site-packages/redbot/core/bot.py", line 929, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/.local/share/Red-DiscordBot/data/discord/cogs/CogManager/cogs/chatter/__init__.py", line 1, in <module>
    from .chat import Chatter
  File "/home/ubuntu/.local/share/Red-DiscordBot/data/discord/cogs/CogManager/cogs/chatter/chat.py", line 6, in <module>
    from chatterbot import ChatBot
ModuleNotFoundError: No module named 'chatterbot'`

**Comment by bobloy** [comment]
See the chatter install instructions [here](https://github.com/bobloy/Fox-V3/tree/master/chatter)

It looks like you missed this step:
`pip install --no-deps "chatterbot>=1.1"`

**Comment by chris100186** [comment]
Perfect, i messed up and did the command outside the red window. 

Is it currently possible to have the bot respond without having to @ it?

**Comment by bobloy** [comment]
Not at this time. There is a feature request that's like that in #46 . If that's something you also want, leave a comment there
