### ISSUE TITLE
[stealemoji] not saving more then 50 emojis

### ISSUE THREAD

**Issue by givemhell** [bobloy/Fox-V3#155]
I have a 100 emoji cap for both emojis and animated emojis and I get this error when I try to steal more then 50

root@kali:/# cd red
root@kali:/red# redbot atart
Instance with this name doesn't exist. You can create new instance using `redbot-setup` prior to running the bot.
rroot@kali:/red# redbot start
Loading packages...
Sleeping for 48747 seconds
/usr/lib/python3/dist-packages/socks.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Callable
/usr/lib/python3/dist-packages/requests_toolbelt/_compat.py:11: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Mapping, MutableMapping
/usr/lib/python3/dist-packages/tabulate.py:7: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import namedtuple, Iterable
Loaded packages: downloader, Scrub, announcedaily, customping, eventposter, gameroles, massdm, massmove, msgvote, netspeed, onlinestats, otherbot, rssnotifier, say, streamroles, tarot, updatechecker, whoplays, Tube, autodisconnect, bancheck, covid, duel, errorlogs, news, Bio, cooldown, mxl, penis, pressf, region, rift, sticky, stickyroles, uniquename, botstatus, check, autoroom, updatered, steamcommunity, antiphoneclapper, dicetable, tweets, redditpost, stealemoji
Connected to Discord. Getting ready...

______         _           ______ _                       _  ______       _
| ___ \       | |          |  _  (_)                     | | | ___ \     | |
| |_/ /___  __| |  ______  | | | |_ ___  ___ ___  _ __ __| | | |_/ / ___ | |_
|    // _ \/ _` | |______| | | | | / __|/ __/ _ \| '__/ _` | | ___ \/ _ \| __|
| |\ \  __/ (_| |          | |/ /| \__ \ (_| (_) | | | (_| | | |_/ / (_) | |_
\_| \_\___|\__,_|          |___/ |_|___/\___\___/|_|  \__,_| \____/ \___/ \__|

┌──────────────────────────────────┐    ┌────────────────┐
│Unity#0123                        │    │√ Voice         │
│Prefixes: //                      │    │X Docs          │
│Language: en-US                   │    │X Tests         │
│Red Bot Version: 3.4.0            │    └────────────────┘
│Discord.py Version: 1.4.1         │
│Shards: 1                         │
│Storage type: JSON                │
│Servers: 1                        │
│Users: 114                        │
│47 cogs with 118 commands         │
└──────────────────────────────────┘

Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/data/start/cogs/CogManager/cogs/stealemoji/stealemoji.py", line 266, in on_reaction_add
    if await check_guild(guild, emoji):
  File "/root/.local/share/Red-DiscordBot/data/start/cogs/CogManager/cogs/stealemoji/stealemoji.py", line 19, in check_guild
    if len(guild.emojis) >= 100:
AttributeError: 'NoneType' object has no attribute 'emojis'

**Comment by batman202012** [comment]
Still having this issue but it's with the first emoji stolen
