### ISSUE TITLE
Fifo loading problem

### ISSUE THREAD

**Issue by Gcuje** [bobloy/Fox-V3#233]
Hello i try to load the fifo cog but i have this error : 
```

Nov 25 01:16:42 ora-vps-2 python3.11[880749]: [2023-11-25 01:16:42] [ERROR] red: Package loading failed
Nov 25 01:16:42 ora-vps-2 python3.11[880749]: Traceback (most recent call last):
Nov 25 01:16:42 ora-vps-2 python3.11[880749]:   File "/home/ubuntu/redenv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 188, in _load
Nov 25 01:16:42 ora-vps-2 python3.11[880749]:     await bot.load_extension(spec)
Nov 25 01:16:42 ora-vps-2 python3.11[880749]:   File "/home/ubuntu/redenv/lib/python3.11/site-packages/redbot/core/bot.py", line 1686, in load_extension
Nov 25 01:16:42 ora-vps-2 python3.11[880749]:     await lib.setup(self)
Nov 25 01:16:42 ora-vps-2 python3.11[880749]:   File "/home/ubuntu/.local/share/Red-DiscordBot/data/redbot/cogs/CogManager/cogs/fifo/__init__.py", line 19, in setup
Nov 25 01:16:42 ora-vps-2 python3.11[880749]:     await cog.initialize()
Nov 25 01:16:42 ora-vps-2 python3.11[880749]:   File "/home/ubuntu/.local/share/Red-DiscordBot/data/redbot/cogs/CogManager/cogs/fifo/fifo.py", line 130, in initialize
Nov 25 01:16:42 ora-vps-2 python3.11[880749]:     await self.jobstore.load_from_config()
Nov 25 01:16:42 ora-vps-2 python3.11[880749]:   File "/home/ubuntu/.local/share/Red-DiscordBot/data/redbot/cogs/CogManager/cogs/fifo/redconfigjobstore.py", line 43, in load_from_config
Nov 25 01:16:42 ora-vps-2 python3.11[880749]:     job = await self._decode_job(job)
Nov 25 01:16:42 ora-vps-2 python3.11[880749]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 25 01:16:42 ora-vps-2 python3.11[880749]:   File "/home/ubuntu/.local/share/Red-DiscordBot/data/redbot/cogs/CogManager/cogs/fifo/redconfigjobstore.py", line 86, in _decode_job
Nov 25 01:16:42 ora-vps-2 python3.11[880749]:     job_state = pickle.loads(base64.b64decode(job_state))
Nov 25 01:16:42 ora-vps-2 python3.11[880749]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 25 01:16:42 ora-vps-2 python3.11[880749]: ModuleNotFoundError: No module named 'backports.zoneinfo'

```

What can i do? Thank you!

**Comment by Ekansh38** [comment]
hello I would like to try and fix this
