### ISSUE TITLE
[PlantTycoon] Bundled_data not existing

### ISSUE THREAD

**Issue by bobloy** [bobloy/Fox-V3#35]
```
Exception during loading of cog
Traceback (most recent call last):
  File "/~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/redbot/core/core_commands.py", line 96, in _load
    await bot.load_extension(spec)
  File "/~/.pyenv/versions/3.6.6/lib/python3.6/site-packages/redbot/core/bot.py", line 231, in load_extension
    lib.setup(self)
  File "/~/bot/cogs/CogManager/cogs/recyclingplant/__init__.py", line 7, in setup
    plant = RecyclingPlant(bot)
  File "/~/bot/cogs/CogManager/cogs/recyclingplant/recyclingplant.py", line 21, in __init__
    with open(self.junk_path) as json_data:
FileNotFoundError: [Errno 2] No such file or directory: '/~/bot/cogs/RecyclingPlant/bundled_data/junk.json'
```

I fixed it by creating bundled_data folder inside the cog's data folder and copy pasting junk.json from the repo path.

**Comment by bobloy** [comment]
Seems to be mainly a problem with failing to `load_bundled_data`, and using `addpath` to add cogs
