### ISSUE TITLE
Audiotrivia not working with newest redbot versions

### ISSUE THREAD

**Issue by pabloleban** [bobloy/Fox-V3#50]
Im getting

`[18/03/2019 00:13] ERROR events on_command_error 207: Exception in command 'audiotrivia'
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Admin\Desktop\obesin\cogs\CogManager\cogs\audiotrivia\audiotrivia.py", line 93, in audiotrivia
    notify = await self.audio.config.notify()
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\redbot\core\config.py", line 642, in __getattr__
    return getattr(global_group, item)
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\redbot\core\config.py", line 241, in __getattr__
    raise AttributeError("'{}' is not a valid registered Group or value.".format(item))
AttributeError: 'notify' is not a valid registered Group or value.`

When trying to run `!audiotrivia plab-games`

Trying with the latest Redbot version (3.0.2)

**Comment by camjac251** [comment]
I get this too with all categories

**Comment by Ianardo-DiCaprio** [comment]
This issue has been fixed and the issue can now be closed.
