### ISSUE TITLE
InfoChannel Does Not Toggle OnlineCount or BotCount

### ISSUE THREAD

**Issue by LGACode** [bobloy/Fox-V3#72]
The command `infochannel set` does not appear to actually toggle the OnlineCount or BotCount channels. Channels are not created even after cycling toggle, only Total Humans is displayed. Additionally, when switching InfoChannel on or off, the InfoChannelSet options are reset to disabled. They should instead preserve their settings.

**Comment by jack1142** [comment]
This can also cause this exception:
```
Traceback (most recent call last):
  File "/root/.pyenv/version/3.8.1/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/AAA/REDbot/cogs/CogManager/cogs/infochannel.infochannel.py", line 215, in on_member_update
    await self.update_infochannel(after.guild)
  File "/AAA/REDbot/cogs/CogManager/cogs/infochannel.infochannel.py", line 200, in update_infochannel
    await onlinechannel.edit(reason="InfoChannel update", name=name)
AttributeError: 'NoneType' object has no attribute 'edit'
```
