### ISSUE TITLE
[QRInvite] Error When Creating QR Code

### ISSUE THREAD

**Issue by LGACode** [bobloy/Fox-V3#74]
```python
Exception in command 'qrinvite'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/app/cogs/CogManager/cogs/qrinvite/qrinvite.py", line 66, in qrinvite
    image_path = path / (ctx.guild.icon + "." + extension)
NameError: name 'extension' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'extension' is not defined
```

**Comment by ShadCamelion** [comment]
Check if in line 63 is a typo.
In line 66 rename "extension" to "extention".
Also check line 73.

**Comment by bobloy** [comment]
This should now be resolved
