### ISSUE TITLE
Lovecalculator gives error upon using command

### ISSUE THREAD

**Issue by Kavalll** [bobloy/Fox-V3#89]
Trying to get the lovecalculator to work but every time i run the command i get the same issue
I installed BeautifulSoup thinking it would fix it but it didn't. Is the cog just outdated perhaps? Would love to see it work but from my tiny amount of coding knowledge i couldn't find any reason why it wouldn't work

` [2020-06-16 15:04:09] [ERROR] red: Exception in command 'lovecalculator'
Traceback (most recent call last):
  File "c:\programs\redenv\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Kaval\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\bestbot\cogs\CogManager\cogs\lovecalculator\lovecalculator.py", line 30, in lovecalculator
    soup_object = BeautifulSoup(await response.text(), "html.parser")
  File "c:\programs\redenv\lib\site-packages\aiohttp\client_reqrep.py", line 1009, in text
    await self.read()
  File "c:\programs\redenv\lib\site-packages\aiohttp\client_reqrep.py", line 973, in read
    self._body = await self.content.read()
  File "c:\programs\redenv\lib\site-packages\aiohttp\streams.py", line 358, in read
    block = await self.readany()
  File "c:\programs\redenv\lib\site-packages\aiohttp\streams.py", line 380, in readany
    await self._wait('readany')
  File "c:\programs\redenv\lib\site-packages\aiohttp\streams.py", line 296, in _wait
    await waiter
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed`

**Comment by bobloy** [comment]
There is a problem with scraping lovecalculator currently. I'm investigating alternatives.
