### ISSUE TITLE
[Audiotrivia] If the audio fails to play because the video is unavailable, the cog stops working

### ISSUE THREAD

**Issue by pabloleban** [bobloy/Fox-V3#92]

**Comment by lumpycustard** [comment]
Fails to play anything. Log shows the following:

`Traceback (most recent call last):
File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
ret = await coro(*args, **kwargs)
File "/data/cogs/CogManager/cogs/qrinvite/qrinvite.py", line 100, in qrinvite
await ctx.send(file=discord.File(png_fp.read(), "qrcode.png"))
File "/data/venv/lib/python3.8/site-packages/discord/file.py", line 73, in __init__
self.fp = open(fp, 'rb')
ValueError: embedded null byte
/data/venv/lib/python3.8/site-packages/lavalink/rest_api.py:349: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead

log.warn("get_tracks() is now deprecated. Please switch to using load_tracks().")
[2020-09-05 20:52:58] [WARNING] red.core.lavalink: get_tracks() is now deprecated. Please switch to using load_tracks().

[2020-09-05 20:54:11] [WARNING] red.core.lavalink: get_tracks() is now deprecated. Please switch to using load_tracks().`

**Comment by WhynautTV** [comment]
bumping issue, getting the same error as lumpycustard. Bot joins VC, does nothing for a few seconds, then disconnects. Even tried editing the audiosession.py to use load_tracks, the error disappears but the cog still doesn't function.
