### ISSUE TITLE
[StealEmoji] bot not saving emojis

### ISSUE THREAD

**Issue by cry8wolf9** [bobloy/Fox-V3#99]
getting this error when the bot tries to save the emoji. 
Also is there a way to purge the list of emojis it has seen?

```
Ignoring` exception in on_reaction_add
Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/RedBotNoz/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/pi/Bots/Red/cogs/CogManager/cogs/stealemoji/stealemoji.py", line 125, in on_reaction_add
    img = await fetch_img(session, emoji.url)
  File "/home/pi/Bots/Red/cogs/CogManager/cogs/stealemoji/stealemoji.py", line 12, in fetch_img
    async with session.get(url) as response:
  File "/home/pi/.pyenv/versions/RedBotNoz/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/pi/.pyenv/versions/RedBotNoz/lib/python3.8/site-packages/aiohttp/client.py", line 380, in _request
    url = URL(str_or_url)
  File "/home/pi/.pyenv/versions/RedBotNoz/lib/python3.8/site-packages/yarl/__init__.py", line 149, in __new__
    raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str
Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/RedBotNoz/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/pi/Bots/Red/cogs/CogManager/cogs/stealemoji/stealemoji.py", line 125, in on_reaction_add
    img = await fetch_img(session, emoji.url)
  File "/home/pi/Bots/Red/cogs/CogManager/cogs/stealemoji/stealemoji.py", line 12, in fetch_img
    async with session.get(url) as response:
  File "/home/pi/.pyenv/versions/RedBotNoz/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/pi/.pyenv/versions/RedBotNoz/lib/python3.8/site-packages/aiohttp/client.py", line 380, in _request
    url = URL(str_or_url)
  File "/home/pi/.pyenv/versions/RedBotNoz/lib/python3.8/site-packages/yarl/__init__.py", line 149, in __new__
    raise TypeError("Constructor parameter should be str")
TypeError: Constructor parameter should be str

```

**Comment by bobloy** [comment]
Thank you for reporting this. 
I've got a fix already on the `stealemoji_develop` branch, but it's not ready yet since there are other bugs where it saves duplicate emojis.
